version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python3 -m uvicorn --app-dir /app/ main:app --host 0.0.0.0 --port 80 --workers 1
    restart: always
    volumes:
      - ./src/:/app
    env_file:
      - docker/.env
    ports:
      - "80:80"

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - docker/.env
    ports:
      - "5432:5432"

volumes:
  db: