version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python3 -m uvicorn --app-dir /app/ main:app --host 0.0.0.0 --port 8001 --workers 1
    container_name: auth_service
    restart: always
    volumes:
      - ./src/:/app
    env_file:
      - docker/.env
    networks:
      - default
      - mysibsau

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - docker/.env

volumes:
  db:

networks:
  mysibsau:
    external: true