FROM python:3.10 as builder

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


FROM python:3.10-alpine as production

WORKDIR app

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages